--create table FACTOR_VARIABLES_BCK as SELECT * FROM FACTOR_VARIABLES;
--create table FACTOR_TIME_SERIES_BCK as SELECT * FROM FACTOR_TIME_SERIES;
--CREATE TABLE FACTOR_FITTED_MODEL_BCK as SELECT * FROM FACTOR_FITTED_MODEL;
--create table FACTOR_FITTED_PARAMETER_BCK as SELECT * FROM FACTOR_FITTED_PARAMETER;
--create table FACTOR_FITTED_PARAMETER_BCK_1 as SELECT * FROM FACTOR_FITTED_PARAMETER;
--TRUNCATE TABLE FACTOR_FITTED_PARAMETER_BCK_1;
insert into FACTOR_FITTED_PARAMETER_BCK_1 ( select * from FACTOR_FITTED_PARAMETER_BCK);